/**
 * NeoJS — Renderer: patching
 * 
 * Applies patches generated by diff() to the real DOM.
 */

import { PatchTypes } from './diff.js';
import { createEl } from './render.js';

/**
 * Patch a real DOM element.
 * @param {Node} el - The DOM element to patch.
 * @param {Array} patches - Patches to apply.
 */
export function patch(el, patches) {
    if (!patches || patches.length === 0) return;

    patches.forEach(p => {
        switch (p.type) {
            case PatchTypes.TEXT:
                el.textContent = p.text;
                break;

            case PatchTypes.PROPS:
                p.props.forEach(({ key, value }) => {
                    if (value === null) {
                        el.removeAttribute(key);
                    } else if (key.startsWith('on')) {
                        // Basic re-binding (not optimized)
                        const eventName = key.slice(2).toLowerCase();
                        // In a real framework, we'd need to track and remove old listeners
                        el.addEventListener(eventName, value);
                    } else {
                        el.setAttribute(key, value);
                    }
                });
                break;

            case PatchTypes.REPLACE:
                const newNode = createEl(p.newVNode);
                el.parentNode.replaceChild(newNode, el);
                break;

            case PatchTypes.REORDER:
                // Simplifying reorder for this demonstration
                // Just re-handling children based on the child patches
                p.patches.forEach(cp => {
                    if (cp.type === 'ADD') {
                        el.appendChild(createEl(cp.node));
                    } else if (cp.type === 'REMOVE') {
                        el.removeChild(el.childNodes[cp.index]);
                    } else if (cp.type === 'UPDATE') {
                        patch(el.childNodes[cp.index], cp.patches);
                    }
                });
                break;
        }
    });
}
